// Code generated by some tool. DO NOT EDIT.

package linedirective

import (
	"context"

	"github.com/rs/zerolog/log"
)

// Generated files are always skipped, even below a //line directive.
//
//line generated.tmpl:1
func badNoCtxInGeneratedBelowLineDirective(ctx context.Context) {
	log.Info().Msg("no context in generated file")
}
