// Code generated by some tool. DO NOT EDIT.

package filefilterskip

import (
	"context"

	"github.com/rs/zerolog"
)

// badNoCtxInGenerated would normally be reported, but generated files are always skipped.
// This file should not be analyzed - no diagnostic expected.
func badNoCtxInGenerated(ctx context.Context, log zerolog.Logger) {
	log.Info().Msg("no context in generated file")
}
