package main

import (
	"errors"
	"maps"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// e2eModule is a module analyzed by the built binary. Each package is run on
// its own. The zerolog stub under testdata replaces the real module, so the
// test needs no network.
var e2eModule = map[string]string{
	"go.mod": `module example.com/repro

go 1.24

require github.com/rs/zerolog v1.35.1

replace github.com/rs/zerolog => ./zerolog
`,
	"ignore/a.go": `package ignore

import (
	"context"

	"github.com/rs/zerolog/log"
)

//line fake.tmpl:1
func Handle(ctx context.Context) {
	log.Info().Msg("hello") //zerologlintctx:ignore
}
`,
	"ignorectl/a.go": `package ignorectl

import (
	"context"

	"github.com/rs/zerolog/log"
)

func Handle(ctx context.Context) {
	log.Info().Msg("hello") //zerologlintctx:ignore
}
`,
	"blockline/a.go": `package blockline

import (
	"context"

	"github.com/rs/zerolog/log"
)

func Handle(ctx context.Context) {
	//zerologlintctx:ignore
	/*line a.go:50*/ log.Info().Msg("hello")
}
`,
	"blockctl/a.go": `package blockctl

import (
	"context"

	"github.com/rs/zerolog/log"
)

func Handle(ctx context.Context) {
	//zerologlintctx:ignore
	/* note */ log.Info().Msg("hello")
}
`,
	"gen/a.go": `// Code generated by hand for repro. DO NOT EDIT.

package gen

import (
	"context"

	"github.com/rs/zerolog/log"
)

//line fake.tmpl:1
func Handle(ctx context.Context) {
	log.Info().Msg("hello")
}
`,
	"genctl/a.go": `// Code generated by hand for repro. DO NOT EDIT.

package genctl

import (
	"context"

	"github.com/rs/zerolog/log"
)

func Handle(ctx context.Context) {
	log.Info().Msg("hello")
}
`,
	"report/a.go": `package report

import (
	"context"

	"github.com/rs/zerolog/log"
)

//line fake.tmpl:1
func Handle(ctx context.Context) {
	log.Info().Msg("hello")
}
`,
}

func TestE2ELineDirective(t *testing.T) {
	bin := filepath.Join(t.TempDir(), "zerologlintctx")
	build := exec.Command("go", "build", "-o", bin, ".")
	if out, err := build.CombinedOutput(); err != nil {
		t.Fatalf("go build: %v\n%s", err, out)
	}

	dir := e2eWriteModule(t)

	tests := []struct {
		pkg      string
		wantOut  []string
		wantCode int
	}{
		{pkg: "ignore", wantCode: 0},
		{pkg: "ignorectl", wantCode: 0},
		{pkg: "blockline", wantCode: 0},
		{pkg: "blockctl", wantCode: 0},
		{pkg: "gen", wantCode: 0},
		{pkg: "genctl", wantCode: 0},
		{
			// Reported positions stay adjusted by //line.
			pkg:      "report",
			wantOut:  []string{filepath.Join(dir, "report", "fake.tmpl") + ":2: zerolog call chain missing .Ctx(ctx)"},
			wantCode: 3,
		},
	}
	for _, tt := range tests {
		t.Run(tt.pkg, func(t *testing.T) {
			cmd := exec.Command(bin, "./"+tt.pkg+"/")
			cmd.Dir = dir
			cmd.Env = append(os.Environ(), "GOFLAGS=-mod=mod", "GOPROXY=off", "GOWORK=off")
			out, err := cmd.CombinedOutput()

			code := 0
			if exitErr, ok := errors.AsType[*exec.ExitError](err); ok {
				code = exitErr.ExitCode()
			} else if err != nil {
				t.Fatalf("run: %v", err)
			}

			var gotOut []string
			if s := strings.TrimSpace(string(out)); s != "" {
				gotOut = strings.Split(s, "\n")
			}
			if strings.Join(gotOut, "\n") != strings.Join(tt.wantOut, "\n") || code != tt.wantCode {
				t.Errorf("exit %d, output:\n%s\nwant exit %d, output:\n%s",
					code, strings.Join(gotOut, "\n"), tt.wantCode, strings.Join(tt.wantOut, "\n"))
			}
		})
	}
}

// e2eWriteModule writes e2eModule and a copy of the zerolog stub into a
// temporary directory and returns its path.
func e2eWriteModule(t *testing.T) string {
	t.Helper()
	dir, err := filepath.EvalSymlinks(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}

	files := make(map[string]string, len(e2eModule)+3)
	maps.Copy(files, e2eModule)
	files["zerolog/go.mod"] = "module github.com/rs/zerolog\n\ngo 1.24\n"
	stub := filepath.Join("..", "..", "testdata", "src", "github.com", "rs", "zerolog")
	for _, name := range []string{"zerolog.go", "log/log.go"} {
		src, err := os.ReadFile(filepath.Join(stub, filepath.FromSlash(name)))
		if err != nil {
			t.Fatal(err)
		}
		files["zerolog/"+name] = string(src)
	}

	for name, src := range files {
		path := filepath.Join(dir, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(src), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return dir
}
