// Code generated by some tool. DO NOT EDIT.

package filefilter

import (
	"context"

	"github.com/rs/zerolog"
)

// badNoCtxInGenerated would normally be reported, but generated files are always skipped.
// This file should not be analyzed - no diagnostic expected.
func badNoCtxInGenerated(ctx context.Context, log zerolog.Logger) {
	log.Info().Msg("no context in generated file")
}

// Directives that do nothing are not reported in a generated file either.
func badDirectivesInGenerated(ctx context.Context, log zerolog.Logger) {
	//zerologlintctx:ignre
	//zerologlintctx:ignore intentionally detached
	// zerologlintctx:ignore
	log.Info().Ctx(ctx).Msg("ok")
}
